### ISSUE TITLE
Getting error The term 'Get-PoliciesAssignedToServicePrincipal' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by ghost** [kaevans/spsaml11#1]
Getting error at line #3 in step #6 at article: https://docs.microsoft.com/en-us/office365/enterprise/using-azure-ad-for-sharepoint-server-authentication.

"PS C:\> $saml2policyid = Get-PoliciesAssignedToServicePrincipal -servicePrincipalId $objectid | ?{$_.di
splayName -EQ "TokenIssuancePolicy"} | select objectId
Get-PoliciesAssignedToServicePrincipal : The term 'Get-PoliciesAssignedToServicePrincipal' is not recognized as the
name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:18
+ $saml2policyid = Get-PoliciesAssignedToServicePrincipal -servicePrinc ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-PoliciesAssignedToServicePrincipal:String) [], CommandNotFoundExcep
   tion
    + FullyQualifiedErrorId : CommandNotFoundException"

**Comment by kaevans** [comment]
Make sure you are following directions to execute the Initialize.ps1 and MSGraphTokenLifetimePolicy.psm1 files as stated in the article.

> This article refers to code samples for interacting with Azure Active Directory Graph. You can download the code samples [here](https://github.com/kaevans/spsaml11/tree/master/scripts).

**Comment by ghost** [comment]
PS code snippet in the article is missing Import-Module "file path of MSGraphTokenLifetimePolicy". Please update the article.

**Comment by kaevans** [comment]
@balajimadgundi The import-module command is there for the Initialize.ps1 file. In other PowerShell commands, the instructions tell you to open the SharePoint shell, so import-module is not necessary. 

`Import-Module <file path of Initialize.ps1>`
