### ISSUE TITLE
Error in MSGraphTokenLifetimePolicy script 

### ISSUE THREAD

**Issue by unnieayilliath** [kaevans/spsaml11#4]
I am getting below error in the powershell when I run the AssignSaml1PolicyToAppPrincipal powershell script.

GetPoliciesAssignedToEntityUrl: Using graph endpoint: https://graph.windows.net
entity: servicePrincipals entityId: d23010a6-e4ad-4908-9094-46be253bf267
HTTP GET https://graph.windows.net/myorganization/servicePrincipals/d23010a6-e4a
d-4908-9094-46be253bf267/policies?api-version=1.6
Invoke-RestMethod : The 'Content-Type' header must be modified using the
appropriate property or method.
Parameter name: name
At D:\Unnie\AAD Integration\MSGraphTokenLifetimePolicy.psm1:339 char:15
+     $result = Invoke-RestMethod @parameters
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], ArgumentE
   xception
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Co
   mmands.InvokeRestMethodCommand

The following TokenIssuancePolicy policies are assigned to the service principal
.

Only a single policy can be assigned to the service principal. Removing the exis
ting policy with ID
ValidateArgument : PolicyId is null or empty
At D:\Unnie\AAD Integration\MSGraphTokenLifetimePolicy.psm1:133 char:5
+     ValidateArgument -argName "PolicyId" -argument $policyId
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,ValidateArgument

AssignPolicyToEntity: Using graph endpoint: https://graph.windows.net entity: se
rvicePrincipals entityId: d23010a6-e4ad-4908-9094-46be253bf267
HTTP DELETE https://graph.windows.net/myorganization/servicePrincipals/d23010a6-
e4ad-4908-9094-46be253bf267/$links/policies/?api-version=1.6
Invoke-RestMethod : The 'Content-Type' header must be modified using the
appropriate property or method.
Parameter name: name
At D:\Unnie\AAD Integration\MSGraphTokenLifetimePolicy.psm1:339 char:15
+     $result = Invoke-RestMethod @parameters
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], ArgumentE
   xception
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Co
   mmands.InvokeRestMethodCommand

Adding the new SAML 1.1 TokenIssuancePolicy
GetEntityUrl: Using graph endpoint: https://graph.windows.net entity: policies e
ntityId:
HTTP POST https://graph.windows.net/myorganization/policies/?api-version=1.6
{"displayName":"SPSAML11","type":"TokenIssuancePolicy","definition":["{\"TokenIs
suancePolicy\":{\"TokenResponseSigningPolicy\":\"TokenOnly\",\"SamlTokenVersion\
":\"1.1\",\"SigningAlgorithm\":\"http://www.w3.org/2001/04/xmldsig-more#rsa-sha2
56\",\"Version\":1}}"]}
Invoke-RestMethod : The 'Content-Type' header must be modified using the
appropriate property or method.
Parameter name: name
At D:\Unnie\AAD Integration\MSGraphTokenLifetimePolicy.psm1:339 char:15
+     $result = Invoke-RestMethod @parameters
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], ArgumentE
   xception
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Co
   mmands.InvokeRestMethodCommand

Assigning the new SAML 1.1 TokenIssuancePolicy .objectId to the service principa
l d23010a6-e4ad-4908-9094-46be253bf267
ValidateArgument : PolicyId is null or empty
At D:\Unnie\AAD Integration\MSGraphTokenLifetimePolicy.psm1:123 char:5
+     ValidateArgument -argName "PolicyId" -argument $policyId
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
   tion
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
   n,ValidateArgument

AssignPolicyToEntity: Using graph endpoint: https://graph.windows.net entity: se
rvicePrincipals entityId: d23010a6-e4ad-4908-9094-46be253bf267
GetEntityUrl: Using graph endpoint: https://graph.windows.net entity: policies e
ntityId:
HTTP POST https://graph.windows.net/myorganization/servicePrincipals/d23010a6-e4
ad-4908-9094-46be253bf267/$links/policies?api-version=1.6
{"url":"https://graph.windows.net/myorganization/policies/?api-version=1.6"}
Invoke-RestMethod : The 'Content-Type' header must be modified using the
appropriate property or method.
Parameter name: name
At D:\Unnie\AAD Integration\MSGraphTokenLifetimePolicy.psm1:339 char:15
+     $result = Invoke-RestMethod @parameters
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-RestMethod], ArgumentE
   xception
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Co
   mmands.InvokeRestMethodCommand

Any ideas?

**Comment by unnieayilliath** [comment]
Hi am back from vacation and I have a fix for this issue.
In MSGraphTokenLifetimePolicy.ps1 file, inside InvokeMSGraphAPI method change the parameters as below:
$parameters = @{
"Method" = $HttpMethod;
"Uri" = $uri;
"Headers" = @{"Authorization"=$authHeader; "Content"="application/json"};
**"ContentType" ="application/json"**
}

**Comment by kaevans** [comment]
Thank you! Fixed in commit https://github.com/kaevans/spsaml11/commit/0e0a290eae64413fc12662d3aec43ea8f99542f5.
